# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YouTubeSampleSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 440)
        MainWindow.setMinimumSize(QtCore.QSize(860, 440))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.timePeriodQLabel = QtWidgets.QLabel(self.centralwidget)
        self.timePeriodQLabel.setGeometry(QtCore.QRect(30, 200, 600, 31))
        self.timePeriodQLabel.setObjectName("timePeriodQLabel")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(700, 350, 141, 31))
        self.downloadButton.setObjectName("downloadButton")
        self.YouTubeSampleSearchLabel = QtWidgets.QLabel(self.centralwidget)
        self.YouTubeSampleSearchLabel.setGeometry(QtCore.QRect(10, 20, 841, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.YouTubeSampleSearchLabel.setFont(font)
        self.YouTubeSampleSearchLabel.setObjectName("YouTubeSampleSearchLabel")
        self.timePeriodLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.timePeriodLineEdit.setGeometry(QtCore.QRect(30, 160, 121, 31))
        self.timePeriodLineEdit.setObjectName("timePeriodLineEdit")
        self.genreLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.genreLineEdit.setGeometry(QtCore.QRect(530, 160, 121, 31))
        self.genreLineEdit.setObjectName("genreLineEdit")
        self.genreQLabel = QtWidgets.QLabel(self.centralwidget)
        self.genreQLabel.setGeometry(QtCore.QRect(530, 200, 600, 31))
        self.genreQLabel.setObjectName("genreQLabel")
        self.fileLocationTextEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLocationTextEdit.setGeometry(QtCore.QRect(20, 300, 631, 31))
        self.fileLocationTextEdit.setObjectName("fileLocationTextEdit")
        self.videoQualityBox = QtWidgets.QComboBox(self.centralwidget)
        self.videoQualityBox.setGeometry(QtCore.QRect(20, 350, 631, 31))
        self.videoQualityBox.setCurrentText("")
        self.videoQualityBox.setObjectName("videoQualityBox")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(700, 160, 141, 31))
        self.searchButton.setObjectName("searchButton")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(700, 300, 141, 31))
        self.browseButton.setObjectName("browseButton")
        self.regionLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.regionLineEdit.setGeometry(QtCore.QRect(280, 160, 121, 31))
        self.regionLineEdit.setObjectName("regionLineEdit")
        self.regionQLabel = QtWidgets.QLabel(self.centralwidget)
        self.regionQLabel.setGeometry(QtCore.QRect(280, 200, 600, 31))
        self.regionQLabel.setObjectName("regionQLabel")
        self.youTubeURLTextEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.youTubeURLTextEdit.setGeometry(QtCore.QRect(20, 240, 631, 31))
        self.youTubeURLTextEdit.setObjectName("youTubeURLTextEdit")
        self.convertURLButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertURLButton.setGeometry(QtCore.QRect(700, 240, 141, 31))
        self.convertURLButton.setObjectName("convertURLButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timePeriodQLabel.setText(_translate("MainWindow", "time period"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.YouTubeSampleSearchLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">YouTube Sample Search</p></body></html>"))
        self.genreQLabel.setText(_translate("MainWindow", "genre"))
        self.fileLocationTextEdit.setText(_translate("MainWindow", "Select File Location"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.regionQLabel.setText(_translate("MainWindow", "region"))
        self.youTubeURLTextEdit.setText(_translate("MainWindow", "Enter YouTube URL here"))
        self.convertURLButton.setText(_translate("MainWindow", "Convert URL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
